name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Remove Git Files
        run: |
          rm -rf .git
          rm -rf .github
          rm -rf .vscode
          rm -f .gitignore
          rm -f .gitattributes
          rm -f .editorconfig

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftps
          port: 21
          security: loose

          server-dir: /www/bms/

          state-name: .ftp-deploy-sync-state.json

          exclude: |
            **/.git*
            **/.github/**
            **/.vscode/**
            .gitignore
            .gitattributes
            .editorconfig
            .env*
            *.log
            *.lock
            application/cache/**
            application/logs/**