name: FTP Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.git/**'
      - '.github/**'
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Remove Git Files
        run: |
          rm -rf .git .github
          rm -f .gitignore .gitattributes .editorconfig

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftps
          port: 21
          security: loose

          server-dir: /www/bms/

          exclude: |
            **/.git*
            **/.github/**
            .env*
            *.log
            *.lock
            application/cache/**
            application/logs/**